/**
 * This class is generated by jOOQ
 */
package com.test.jooq;


import com.test.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in tmp
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table tmp.user
	 */
	public static final User USER = com.test.jooq.tables.User.USER;
}
